// <auto-generated />
namespace WinSite.IdentityMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class passwordhashremove : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(passwordhashremove));
        
        string IMigrationMetadata.Id
        {
            get { return "202402201756519_password hash remove"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
